# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='demand',
            name='itemId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.MenuItems'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='categoryId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.Categories'),
        ),
    ]
