# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171014_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='MenuItem',
        ),
    ]
