# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20171014_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='itemId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.MenuItem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='categoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Category'),
        ),
    ]
